image: node:18.2.0

before_script:
  - cd server/
  - npm install
cache:
  paths:
  - server/node_modules/

.default_rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
      allow_failure: false

stages:
  - lint
  - test

linter-job:
  stage: lint
  rules:
    !reference [.default_rules, rules]
  script:
    - npm run lint

test-job:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  rules:
    !reference [.default_rules, rules]
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - server/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: server/coverage/cobertura-coverage.xml
