image: node:18.2.0

before_script:
  - cd server/
  - npm install
cache:
  paths:
  - node_modules

stages:
  - lint
  - test

linter-job:
  stage: lint
  script:
    - npm run lint

unit-test-job:
  stage: test
  script:
    - npm t
