image: node:18.2.0

before_script:
  - cd server/
  - npm install
cache:
  paths:
  - node_modules

stages:
  - lint
  - test

linter-job:
  stage: lint
  script:
    - npm run lint

test-job:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - server/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: server/coverage/cobertura-coverage.xml
