version: '3.7' # For more information about the version, see https://docs.docker.com/compose/compose-file/compose-versioning/
services:
  crypto-monitor-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
  crypto-monitor-client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - PORT=${WEB_PORT}
      - VITE_SERVER_PORT=${PORT}
