version: '3.7' # For more information about the version, see https://docs.docker.com/compose/compose-file/compose-versioning/
services:
  crypto-monitor-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
  crypto-monitor-client:
    build:
      context: ../client
      dockerfile: Dockerfile
    ports:
      - ${CLI_PORT}:${CLI_PORT}
    env_file:
      - ../client/.env
    environment:
      - PORT=${CLI_PORT}
